[loggers]
keys=root,customLogger

[handlers]
keys=consoleHandler

[formatters]
keys=customFormatter

[logger_root]
level=DEBUG
handlers=consoleHandler

[logger_customLogger]
level=DEBUG
handlers=consoleHandler
qualname=customLogger
propagate=0

[handler_consoleHandler]
class=FileHandler
level=DEBUG
formatter=customFormatter
args=('custom_log.log',)

[formatter_customFormatter]
format=%(asctime)s - %(name)s - %(levelname)s - %(message)s